#!/usr/bin/env python3
"""按 scripts/kb_manifest.yaml 生成 kb/实验/ 索引卡（幂等）。

用法：
    python scripts/gen_kb_index.py          # 生成/刷新 kb/实验/ 下全部索引卡
    python scripts/gen_kb_index.py --check  # 只校验 manifest 引用的文件/笔记是否存在

约定：
- 索引卡完全由脚本生成（文末有 generated 标记），不要手改；改 manifest 后重跑。
- 章节/概念/练习拆解等手工笔记不会被触碰。
- manifest 删除条目不会自动删除旧卡片，需手动清理 kb/实验/ 下对应文件。
"""
from __future__ import annotations

import argparse
import sys
from pathlib import Path
from urllib.parse import quote

try:
    import yaml
except ImportError:  # pragma: no cover
    sys.exit("需要 PyYAML：pip install pyyaml")

ROOT = Path(__file__).resolve().parent.parent
MANIFEST = ROOT / "scripts" / "kb_manifest.yaml"
OUT_DIR = ROOT / "kb" / "实验"
MARKER = "<!-- generated by scripts/gen_kb_index.py -->"
CREATED = "2026-08-28"  # 固定值保证重跑幂等

ICON_LABELS = {"✅": "已跑通", "📖": "待复现", "🚧": "半成品"}
# 渲染为 markdown 链接的扩展名；目录等其余目标渲染为行内代码
LINK_EXTS = {".py", ".ipynb", ".md", ".json", ".yml", ".yaml", ".zip", ".toml", ".txt"}


def load_manifest() -> dict:
    with open(MANIFEST, encoding="utf-8") as f:
        data = yaml.safe_load(f)
    return {c["chapter"]: c for c in data["chapters"]}


def rel_link(note_dir_depth: int, target: Path) -> str:
    """从 kb/实验/ 笔记指向仓库内文件的 markdown 相对链接。"""
    prefix = "../" * note_dir_depth
    href = quote(str(target).replace("\\", "/"))
    return f"[{target.name}]({prefix}{href})"


def render_source(dir_: str, files: list[str]) -> str:
    base = ROOT / dir_
    parts = []
    for f in files:
        target = base / f
        if target.suffix.lower() in LINK_EXTS and not f.endswith("/"):
            parts.append(rel_link(2, Path(dir_) / f))
        else:
            parts.append(f"`{dir_}/{f}`")
    return " · ".join(parts)


def render_card(ch: dict, item: dict, kind: str) -> tuple[str, str]:
    n = ch["chapter"]
    code = item["code"]
    name = item["name"]
    icon = item.get("icon", ch.get("icon", "📖"))
    status = item.get("status", "未开始")
    dir_ = item.get("dir", f"code/chapter{n}")
    files = item.get("files", [])
    concepts = item.get("concepts", [])
    note_name = f"{kind} {code} · {name}"
    chapter_note = f"第{n:02d}章 · {ch['title']}"

    fm = [
        "---",
        f"chapter: {n}",
        f'code: "{code}"',
        "codes: [" + ", ".join(f'"{f}"' for f in files) + "]",
        f"type: {kind}",
        f'icon: "{icon}"',
        f'dir: "{dir_}"',
        f"status: {status}",
        "created: " + CREATED,
        "tags:",
        "  - 实验",
        "---",
        "",
        f"# {note_name}",
        "",
        f"> {item['desc']}",
        "",
        f"- **类型**：{icon}（{ICON_LABELS.get(icon, '待复现')}）",
        f"- **归属章节**：[[{chapter_note}|第 {n} 章]]",
        f"- **正文**：[[{ch['doc']}|第 {n} 章正文]]",
        f"- **源码目录**：`{dir_}`",
        f"- **源码**：{render_source(dir_, files)}",
    ]
    if concepts:
        fm.append("- **相关概念**：" + " · ".join(f"[[{c}]]" for c in concepts))
    fm += ["", MARKER, ""]
    return note_name, "\n".join(fm)


def generate(manifest: dict) -> int:
    OUT_DIR.mkdir(parents=True, exist_ok=True)
    written = skipped = 0
    for n, ch in sorted(manifest.items()):
        for key, kind in (("experiments", "实验"), ("projects", "项目")):
            for item in ch.get(key) or []:
                note_name, content = render_card(ch, item, kind)
                out = OUT_DIR / f"{note_name}.md"
                if out.exists() and out.read_text(encoding="utf-8") == content:
                    skipped += 1
                    continue
                out.write_text(content, encoding="utf-8", newline="\n")
                written += 1
    total = sum(len(ch.get("experiments") or []) + len(ch.get("projects") or []) for ch in manifest.values())
    print(f"实验索引：共 {total} 张卡片（写入 {written}，无变化 {skipped}）→ kb/实验/")
    return 0


def check(manifest: dict) -> int:
    errors: list[str] = []
    for n, ch in sorted(manifest.items()):
        doc = ROOT / "docs" / f"chapter{n}" / f"{ch['doc']}.md"
        note = ROOT / "kb" / "章节" / f"第{n:02d}章 · {ch['title']}.md"
        if not doc.exists():
            errors.append(f"缺少正文文件：{doc.relative_to(ROOT)}")
        if not note.exists():
            errors.append(f"缺少章节笔记：{note.relative_to(ROOT)}")
        for key in ("experiments", "projects"):
            for item in ch.get(key) or []:
                dir_ = ROOT / item.get("dir", f"code/chapter{n}")
                if not dir_.exists():
                    errors.append(f"缺少源码目录：{item['code']} → {dir_.relative_to(ROOT)}")
                    continue
                for f in item.get("files", []):
                    if f.endswith("/") or not (dir_ / f).exists():
                        if not f.endswith("/"):
                            errors.append(f"缺少源码文件：{item['code']} → {item.get('dir', f'code/chapter{n}')}/{f}")
    if errors:
        print(f"✗ {len(errors)} 处不一致：")
        for e in errors:
            print("  -", e)
        return 1
    print("✓ manifest 与仓库文件、章节笔记全部一致")
    return 0


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--check", action="store_true", help="只校验，不生成")
    args = ap.parse_args()
    manifest = load_manifest()
    return check(manifest) if args.check else generate(manifest)


if __name__ == "__main__":
    sys.exit(main())
